//389. Find the Difference
//Given two strings s and t which consist of only lowercase letters.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Find the letter that was added in t.

#include <iostream>

using namespace std;

class Solution {
public:
    char findTheDifference(string s, string t) {
    	char temp = 0;
    	for (auto i : s) temp ^= i;
    	for (auto i : t) temp ^= i;
    	return temp;
    }
};

int main(){
	Solution testCase;
	string testString1, testString2;
	cout << "please input the first string" << endl;
	getline(cin, testString1);
	cout << "please input the second string" << endl;
	getline(cin, testString2);
	char testResult = testCase.findTheDifference(testString1, testString2);
	cout << "the result is " << testResult << endl;
	return 0;
}